# Generated by Django 2.2.1 on 2019-06-12 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_longue', models.URLField(unique=True)),
                ('code_raccourci', models.CharField(max_length=42)),
                ('date_raccourci', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('pseudo_createur', models.CharField(max_length=42)),
                ('nombre_acces', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date_raccourci'],
            },
        ),
    ]
